name: gencore_epigenetics
version: 1.0
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- samtools=1.3.1
- bcftools=1.3.1
- bedtools=2.25.0
- vcftools=0.1.14
- bwa=0.7.15
- bamtools=2.4.0
- vcflib=1.0.0_rc1
- bowtie2=2.2.8
- numpy=1.11.1
- python=2.7
- macs2=2.1.1.20160309
