name: gencore_de_novo_genomic
version: 1.0
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-app-cpanminus
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- idba=1.1.1
- blat=35
- gatk=3.6
- picard=2.5.0
- prinseq=0.20.4
- augustus=3.2.2
- discovar=52488
- discovardenovo=52488
- blast=2.2.31
- samtools=1.3.1
- bcftools=1.3.1
- bedtools=2.25.0
- vcftools=0.1.14
- freebayes=1.0.2.29
- hmmer=3.1b2
- jellyfish=2.2.3
- kmergenie=1.7016
- genblastg=1.38
- genblasta=1.0.4
- sickle=0.5
- abyss=1.9.0
- velvet=1.2.10
- quast=4.1
- bwa=0.7.15
- bamtools=2.4.0
- vcflib=1.0.0_rc1
- trimmomatic=0.36
- seqtk=1.2
- pear=0.9.6
- bowtie2=2.2.8
- circos=0.69.2
- mira=4.0.2
- spades=3.9.0
- gencore_de_novo_genomic_docs=1.0
