name: gencore_rad_1.0
channels:
  - bioconda
dependencies:
  - perl-hpc-runner-slurm=2.58
  - perl-biox-workflow=1.10
  - perl-biox-workflow-plugin-fileexists=0.13
  - perl-biox-workflow-plugin-filedetails=0.11
  - blat=35
  - blast=2.2.31
  - samtools=1.3.1
  - bcftools=1.3.1
  - bedtools=2.25.0
  - vcftools=0.1.14
  - freebayes=1.0.2.29
  - vcflib=1.0.0_rc1
  - bamtools=2.4.0
  - rainbow=2.0.4
  - seqtk=1.2
  - cd-hit=4.6.4
  - stacks=1.40
  - bowtie2=2.2.8
