name: gencore_1.0

channels:
  - bioconda
  - r
dependencies:
  - perl-app-cpanminus
  - perl-hpc-runner-slurm=2.58
  - perl-biox-workflow=1.10
  - perl-biox-workflow-plugin-fileexists=0.13
  - r-base
  - r-essentials
  - r-ggplot2
  - bioconductor-biocgenerics
