name: gencore_trinity

version: 1.0
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- trinotate=3.0.1
- transdecoder=2.1.0
- trinity=2.2.0
- rsem=1.2.28
- gencore_trinity_docs=1.0
