name: gencore_rnaseq
version: 1.0
build: 0

channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- samtools=1.3.1
- bcftools=1.3.1
- kallisto=0.43.0
- blat=35
- gatk=3.6
- picard=2.5.0
- trimmomatic=0.36
- fastqc=0.11.5
- prinseq=0.20.4
- star=2.5.2a
- vcftools=0.1.14
- bedtools=2.25.0
- vcflib=1.0.0_rc1
- bamtools=2.4.0
- seqtk=1.2
- bowtie2=2.2.8
- tophat=2.1.0
- cufflinks-patch=2.2.1
- r-base=3.3.1
- r-essentials
- r-cairo
- bioconductor-deseq2=1.12.4
- bioconductor-edger=3.14.0
- bioconductor-cummerbund=2.16.0
- bioconductor-genomicranges=1.26.1
- bioconductor-gviz=1.16.5
- bioconductor-biovizbase=1.18.0
- bioconductor-s4vectors=0.12.0
- bioconductor-ballgown=2.2.0
- htseq=0.6.1.post1
- hisat2=2.0.4
- stringtie=1.3.0
