name: gencore_rnaseq_malaria
version: 1.0
build: 0
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- samtools=1.3.1
- bcftools=1.3.1
- kallisto=0.43.0
- blat=35
- gatk=3.5
- picard=2.0.1
- star=2.5.2a
- vcftools=0.1.14
- bedtools=2.25.0
- vcflib=1.0.0_rc1
- bamtools=2.4.0
- seqtk=1.2
- bowtie2=2.2.8
- tophat=2.1.0
- cufflinks=2.2.1
- bioconductor-deseq=1.22.1
- bioconductor-deseq2=1.10.1
- bioconductor-edger=3.14.0
- bioconductor-cummerbund=2.12.1
- htseq=0.6.1.post1
- prinseq=0.20.4
- trimmomatic=0.35
