name: gencore_annotation
version: 1.0
build: 1
channels:
- bioconda
- r
- defaults
- conda-forge
- nyuad-cgsb
dependencies:
- perl-app-cpanminus
- perl-hpc-runner-command=3.1.1
- perl-biox-workflow=1.10
- perl-biox-workflow-plugin-fileexists=0.13
- perl-biox-workflow-plugin-filedetails=0.11
- blat=35
- augustus=3.2.2
- blast=2.2.31
- hmmer=3.1b2
- bwa=0.7.15
- samtools=1.3.1
- bcftools=1.3.1
- bedtools=2.25.0
- vcftools=0.1.14
- vcflib=1.0.0_rc1
- bamtools=2.4.0
- repeatmasker=4.0.6
- rmblast=2.2.28
- trinotate=3.0.1
- transdecoder=2.1.0
- snpeff=4.3
- genblasta=1.0.4
- genblastg=1.38
- jellyfish=2.2.3
- kat=2.0.8
- kmergenie=1.7016
- freebayes=1.0.2.29
- bowtie2=2.2.8
- tophat=2.1.0
- circos=0.69.2
- gencore_annotation_docs=1.0
- pauda=1.0.1
